import{a as S,S as b,i}from"./assets/vendor-BjRz3xa9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();async function u(o,t=1,n=15){try{return(await S.get(BASE_URL,{params:{key:API_KEY,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:n}})).data}catch(s){throw console.error("Error fetching images:",s),s}}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".load-more"),w=new b(".gallery a");function g(o){const t=o.map(({webformatURL:n,largeImageURL:s,tags:e,likes:r,views:l,comments:q,downloads:E})=>`
        <li class="gallery-item">
          <a href="${s}" class="gallery-link">
            <img src="${n}" alt="${e}" class="gallery-image" />
          </a>
          <div class="info">
            <p>❤️ ${r}</p>
            <p>👁️ ${l}</p>
            <p>💬 ${q}</p>
            <p>⬇️ ${E}</p>
          </div>
        </li>
      `).join("");f.insertAdjacentHTML("beforeend",t),w.refresh()}function B(){f.innerHTML=""}function p(){m.classList.add("visible")}function h(){m.classList.remove("visible")}function L(){y.style.display="block"}function d(){y.style.display="none"}let c="",a=1;const v=15,$=document.querySelector(".form");document.querySelector(".gallery");const M=document.querySelector(".load-more");document.querySelector(".loader");$.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.target.elements.searchQuery.value.trim(),!c){i.error({title:"Error",message:"Enter search query"});return}a=1,B(),d(),p();try{const{hits:t,totalHits:n}=await u(c,a);if(t.length===0){i.warning({title:"Oops!",message:"No images found."});return}g(t),a*v<n?L():i.info({title:"End",message:"You've reached the end."})}catch{i.error({title:"Error",message:"Request failed."})}finally{h()}});M.addEventListener("click",async()=>{var o;a+=1,d(),p();try{const{hits:t,totalHits:n}=await u(c,a);g(t);const s=((o=document.querySelector(".gallery-item"))==null?void 0:o.getBoundingClientRect().height)||0;window.scrollBy({top:s*2,behavior:"smooth"}),a*v>=n?(d(),i.info({title:"End",message:"You've reached the end."})):L()}catch{i.error({title:"Error",message:"Loading more failed."})}finally{h()}});
//# sourceMappingURL=index.js.map
