import{S,i}from"./assets/vendor-5ObWk2rO.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();async function u(o,t=1,s=15){try{return(await axios.get(BASE_URL,{params:{key:API_KEY,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:s}})).data}catch(n){throw console.error("Error fetching images:",n),n}}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".load-more"),b=new S(".gallery a");function g(o){const t=o.map(({webformatURL:s,largeImageURL:n,tags:e,likes:r,views:l,comments:q,downloads:E})=>`
        <li class="gallery-item">
          <a href="${n}" class="gallery-link">
            <img src="${s}" alt="${e}" class="gallery-image" />
          </a>
          <div class="info">
            <p>❤️ ${r}</p>
            <p>👁️ ${l}</p>
            <p>💬 ${q}</p>
            <p>⬇️ ${E}</p>
          </div>
        </li>
      `).join("");f.insertAdjacentHTML("beforeend",t),b.refresh()}function w(){f.innerHTML=""}function p(){m.classList.add("visible")}function h(){m.classList.remove("visible")}function L(){y.style.display="block"}function d(){y.style.display="none"}let c="",a=1;const v=15,B=document.querySelector(".form");document.querySelector(".gallery");const $=document.querySelector(".load-more");document.querySelector(".loader");B.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.target.elements.searchQuery.value.trim(),!c){i.error({title:"Error",message:"Enter search query"});return}a=1,w(),d(),p();try{const{hits:t,totalHits:s}=await u(c,a);if(t.length===0){i.warning({title:"Oops!",message:"No images found."});return}g(t),a*v<s?L():i.info({title:"End",message:"You've reached the end."})}catch{i.error({title:"Error",message:"Request failed."})}finally{h()}});$.addEventListener("click",async()=>{var o;a+=1,d(),p();try{const{hits:t,totalHits:s}=await u(c,a);g(t);const n=((o=document.querySelector(".gallery-item"))==null?void 0:o.getBoundingClientRect().height)||0;window.scrollBy({top:n*2,behavior:"smooth"}),a*v>=s?(d(),i.info({title:"End",message:"You've reached the end."})):L()}catch{i.error({title:"Error",message:"Loading more failed."})}finally{h()}});
//# sourceMappingURL=index.js.map
